//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: osmosis/tokenfactory/v1beta1/query.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// Query defines the gRPC querier service.
///
/// Usage: instantiate `Osmosis_Tokenfactory_V1beta1_QueryClient`, then call methods of this protocol to make API calls.
internal protocol Osmosis_Tokenfactory_V1beta1_QueryClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Osmosis_Tokenfactory_V1beta1_QueryClientInterceptorFactoryProtocol? { get }

  func params(
    _ request: Osmosis_Tokenfactory_V1beta1_QueryParamsRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Osmosis_Tokenfactory_V1beta1_QueryParamsRequest, Osmosis_Tokenfactory_V1beta1_QueryParamsResponse>

  func denomAuthorityMetadata(
    _ request: Osmosis_Tokenfactory_V1beta1_QueryDenomAuthorityMetadataRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Osmosis_Tokenfactory_V1beta1_QueryDenomAuthorityMetadataRequest, Osmosis_Tokenfactory_V1beta1_QueryDenomAuthorityMetadataResponse>

  func denomsFromCreator(
    _ request: Osmosis_Tokenfactory_V1beta1_QueryDenomsFromCreatorRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Osmosis_Tokenfactory_V1beta1_QueryDenomsFromCreatorRequest, Osmosis_Tokenfactory_V1beta1_QueryDenomsFromCreatorResponse>
}

extension Osmosis_Tokenfactory_V1beta1_QueryClientProtocol {
  internal var serviceName: String {
    return "osmosis.tokenfactory.v1beta1.Query"
  }

  /// Params returns the total set of minting parameters.
  ///
  /// - Parameters:
  ///   - request: Request to send to Params.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func params(
    _ request: Osmosis_Tokenfactory_V1beta1_QueryParamsRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Osmosis_Tokenfactory_V1beta1_QueryParamsRequest, Osmosis_Tokenfactory_V1beta1_QueryParamsResponse> {
    return self.makeUnaryCall(
      path: "/osmosis.tokenfactory.v1beta1.Query/Params",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeParamsInterceptors() ?? []
    )
  }

  /// Unary call to DenomAuthorityMetadata
  ///
  /// - Parameters:
  ///   - request: Request to send to DenomAuthorityMetadata.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func denomAuthorityMetadata(
    _ request: Osmosis_Tokenfactory_V1beta1_QueryDenomAuthorityMetadataRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Osmosis_Tokenfactory_V1beta1_QueryDenomAuthorityMetadataRequest, Osmosis_Tokenfactory_V1beta1_QueryDenomAuthorityMetadataResponse> {
    return self.makeUnaryCall(
      path: "/osmosis.tokenfactory.v1beta1.Query/DenomAuthorityMetadata",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeDenomAuthorityMetadataInterceptors() ?? []
    )
  }

  /// Unary call to DenomsFromCreator
  ///
  /// - Parameters:
  ///   - request: Request to send to DenomsFromCreator.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func denomsFromCreator(
    _ request: Osmosis_Tokenfactory_V1beta1_QueryDenomsFromCreatorRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Osmosis_Tokenfactory_V1beta1_QueryDenomsFromCreatorRequest, Osmosis_Tokenfactory_V1beta1_QueryDenomsFromCreatorResponse> {
    return self.makeUnaryCall(
      path: "/osmosis.tokenfactory.v1beta1.Query/DenomsFromCreator",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeDenomsFromCreatorInterceptors() ?? []
    )
  }
}

internal protocol Osmosis_Tokenfactory_V1beta1_QueryClientInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when invoking 'params'.
  func makeParamsInterceptors() -> [ClientInterceptor<Osmosis_Tokenfactory_V1beta1_QueryParamsRequest, Osmosis_Tokenfactory_V1beta1_QueryParamsResponse>]

  /// - Returns: Interceptors to use when invoking 'denomAuthorityMetadata'.
  func makeDenomAuthorityMetadataInterceptors() -> [ClientInterceptor<Osmosis_Tokenfactory_V1beta1_QueryDenomAuthorityMetadataRequest, Osmosis_Tokenfactory_V1beta1_QueryDenomAuthorityMetadataResponse>]

  /// - Returns: Interceptors to use when invoking 'denomsFromCreator'.
  func makeDenomsFromCreatorInterceptors() -> [ClientInterceptor<Osmosis_Tokenfactory_V1beta1_QueryDenomsFromCreatorRequest, Osmosis_Tokenfactory_V1beta1_QueryDenomsFromCreatorResponse>]
}

internal final class Osmosis_Tokenfactory_V1beta1_QueryClient: Osmosis_Tokenfactory_V1beta1_QueryClientProtocol {
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Osmosis_Tokenfactory_V1beta1_QueryClientInterceptorFactoryProtocol?

  /// Creates a client for the osmosis.tokenfactory.v1beta1.Query service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Osmosis_Tokenfactory_V1beta1_QueryClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

/// Query defines the gRPC querier service.
///
/// To build a server, implement a class that conforms to this protocol.
internal protocol Osmosis_Tokenfactory_V1beta1_QueryProvider: CallHandlerProvider {
  var interceptors: Osmosis_Tokenfactory_V1beta1_QueryServerInterceptorFactoryProtocol? { get }

  /// Params returns the total set of minting parameters.
  func params(request: Osmosis_Tokenfactory_V1beta1_QueryParamsRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Osmosis_Tokenfactory_V1beta1_QueryParamsResponse>

  func denomAuthorityMetadata(request: Osmosis_Tokenfactory_V1beta1_QueryDenomAuthorityMetadataRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Osmosis_Tokenfactory_V1beta1_QueryDenomAuthorityMetadataResponse>

  func denomsFromCreator(request: Osmosis_Tokenfactory_V1beta1_QueryDenomsFromCreatorRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Osmosis_Tokenfactory_V1beta1_QueryDenomsFromCreatorResponse>
}

extension Osmosis_Tokenfactory_V1beta1_QueryProvider {
  internal var serviceName: Substring { return "osmosis.tokenfactory.v1beta1.Query" }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "Params":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Osmosis_Tokenfactory_V1beta1_QueryParamsRequest>(),
        responseSerializer: ProtobufSerializer<Osmosis_Tokenfactory_V1beta1_QueryParamsResponse>(),
        interceptors: self.interceptors?.makeParamsInterceptors() ?? [],
        userFunction: self.params(request:context:)
      )

    case "DenomAuthorityMetadata":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Osmosis_Tokenfactory_V1beta1_QueryDenomAuthorityMetadataRequest>(),
        responseSerializer: ProtobufSerializer<Osmosis_Tokenfactory_V1beta1_QueryDenomAuthorityMetadataResponse>(),
        interceptors: self.interceptors?.makeDenomAuthorityMetadataInterceptors() ?? [],
        userFunction: self.denomAuthorityMetadata(request:context:)
      )

    case "DenomsFromCreator":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Osmosis_Tokenfactory_V1beta1_QueryDenomsFromCreatorRequest>(),
        responseSerializer: ProtobufSerializer<Osmosis_Tokenfactory_V1beta1_QueryDenomsFromCreatorResponse>(),
        interceptors: self.interceptors?.makeDenomsFromCreatorInterceptors() ?? [],
        userFunction: self.denomsFromCreator(request:context:)
      )

    default:
      return nil
    }
  }
}

internal protocol Osmosis_Tokenfactory_V1beta1_QueryServerInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when handling 'params'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeParamsInterceptors() -> [ServerInterceptor<Osmosis_Tokenfactory_V1beta1_QueryParamsRequest, Osmosis_Tokenfactory_V1beta1_QueryParamsResponse>]

  /// - Returns: Interceptors to use when handling 'denomAuthorityMetadata'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeDenomAuthorityMetadataInterceptors() -> [ServerInterceptor<Osmosis_Tokenfactory_V1beta1_QueryDenomAuthorityMetadataRequest, Osmosis_Tokenfactory_V1beta1_QueryDenomAuthorityMetadataResponse>]

  /// - Returns: Interceptors to use when handling 'denomsFromCreator'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeDenomsFromCreatorInterceptors() -> [ServerInterceptor<Osmosis_Tokenfactory_V1beta1_QueryDenomsFromCreatorRequest, Osmosis_Tokenfactory_V1beta1_QueryDenomsFromCreatorResponse>]
}
