// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: protoc-gen-openapiv2/options/annotations.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

// MARK: - Extension support defined in annotations.proto.

// MARK: - Extension Properties

// Swift Extensions on the exteneded Messages to add easy access to the declared
// extension fields. The names are based on the extension field name from the proto
// declaration. To avoid naming collisions, the names are prefixed with the name of
// the scope where the extend directive occurs.

extension SwiftProtobuf.Google_Protobuf_FieldOptions {

  /// ID assigned by protobuf-global-extension-registry@google.com for gRPC-Gateway project.
  ///
  /// All IDs are the same, as assigned. It is okay that they are the same, as they extend
  /// different descriptor messages.
  var Grpc_Gateway_ProtocGenOpenapiv2_Options_openapiv2Field: Grpc_Gateway_ProtocGenOpenapiv2_Options_JSONSchema {
    get {return getExtensionValue(ext: Grpc_Gateway_ProtocGenOpenapiv2_Options_Extensions_openapiv2_field) ?? Grpc_Gateway_ProtocGenOpenapiv2_Options_JSONSchema()}
    set {setExtensionValue(ext: Grpc_Gateway_ProtocGenOpenapiv2_Options_Extensions_openapiv2_field, value: newValue)}
  }
  /// Returns true if extension `Grpc_Gateway_ProtocGenOpenapiv2_Options_Extensions_openapiv2_field`
  /// has been explicitly set.
  var hasGrpc_Gateway_ProtocGenOpenapiv2_Options_openapiv2Field: Bool {
    return hasExtensionValue(ext: Grpc_Gateway_ProtocGenOpenapiv2_Options_Extensions_openapiv2_field)
  }
  /// Clears the value of extension `Grpc_Gateway_ProtocGenOpenapiv2_Options_Extensions_openapiv2_field`.
  /// Subsequent reads from it will return its default value.
  mutating func clearGrpc_Gateway_ProtocGenOpenapiv2_Options_openapiv2Field() {
    clearExtensionValue(ext: Grpc_Gateway_ProtocGenOpenapiv2_Options_Extensions_openapiv2_field)
  }
}

extension SwiftProtobuf.Google_Protobuf_FileOptions {

  /// ID assigned by protobuf-global-extension-registry@google.com for gRPC-Gateway project.
  ///
  /// All IDs are the same, as assigned. It is okay that they are the same, as they extend
  /// different descriptor messages.
  var Grpc_Gateway_ProtocGenOpenapiv2_Options_openapiv2Swagger: Grpc_Gateway_ProtocGenOpenapiv2_Options_Swagger {
    get {return getExtensionValue(ext: Grpc_Gateway_ProtocGenOpenapiv2_Options_Extensions_openapiv2_swagger) ?? Grpc_Gateway_ProtocGenOpenapiv2_Options_Swagger()}
    set {setExtensionValue(ext: Grpc_Gateway_ProtocGenOpenapiv2_Options_Extensions_openapiv2_swagger, value: newValue)}
  }
  /// Returns true if extension `Grpc_Gateway_ProtocGenOpenapiv2_Options_Extensions_openapiv2_swagger`
  /// has been explicitly set.
  var hasGrpc_Gateway_ProtocGenOpenapiv2_Options_openapiv2Swagger: Bool {
    return hasExtensionValue(ext: Grpc_Gateway_ProtocGenOpenapiv2_Options_Extensions_openapiv2_swagger)
  }
  /// Clears the value of extension `Grpc_Gateway_ProtocGenOpenapiv2_Options_Extensions_openapiv2_swagger`.
  /// Subsequent reads from it will return its default value.
  mutating func clearGrpc_Gateway_ProtocGenOpenapiv2_Options_openapiv2Swagger() {
    clearExtensionValue(ext: Grpc_Gateway_ProtocGenOpenapiv2_Options_Extensions_openapiv2_swagger)
  }
}

extension SwiftProtobuf.Google_Protobuf_MessageOptions {

  /// ID assigned by protobuf-global-extension-registry@google.com for gRPC-Gateway project.
  ///
  /// All IDs are the same, as assigned. It is okay that they are the same, as they extend
  /// different descriptor messages.
  var Grpc_Gateway_ProtocGenOpenapiv2_Options_openapiv2Schema: Grpc_Gateway_ProtocGenOpenapiv2_Options_Schema {
    get {return getExtensionValue(ext: Grpc_Gateway_ProtocGenOpenapiv2_Options_Extensions_openapiv2_schema) ?? Grpc_Gateway_ProtocGenOpenapiv2_Options_Schema()}
    set {setExtensionValue(ext: Grpc_Gateway_ProtocGenOpenapiv2_Options_Extensions_openapiv2_schema, value: newValue)}
  }
  /// Returns true if extension `Grpc_Gateway_ProtocGenOpenapiv2_Options_Extensions_openapiv2_schema`
  /// has been explicitly set.
  var hasGrpc_Gateway_ProtocGenOpenapiv2_Options_openapiv2Schema: Bool {
    return hasExtensionValue(ext: Grpc_Gateway_ProtocGenOpenapiv2_Options_Extensions_openapiv2_schema)
  }
  /// Clears the value of extension `Grpc_Gateway_ProtocGenOpenapiv2_Options_Extensions_openapiv2_schema`.
  /// Subsequent reads from it will return its default value.
  mutating func clearGrpc_Gateway_ProtocGenOpenapiv2_Options_openapiv2Schema() {
    clearExtensionValue(ext: Grpc_Gateway_ProtocGenOpenapiv2_Options_Extensions_openapiv2_schema)
  }
}

extension SwiftProtobuf.Google_Protobuf_MethodOptions {

  /// ID assigned by protobuf-global-extension-registry@google.com for gRPC-Gateway project.
  ///
  /// All IDs are the same, as assigned. It is okay that they are the same, as they extend
  /// different descriptor messages.
  var Grpc_Gateway_ProtocGenOpenapiv2_Options_openapiv2Operation: Grpc_Gateway_ProtocGenOpenapiv2_Options_Operation {
    get {return getExtensionValue(ext: Grpc_Gateway_ProtocGenOpenapiv2_Options_Extensions_openapiv2_operation) ?? Grpc_Gateway_ProtocGenOpenapiv2_Options_Operation()}
    set {setExtensionValue(ext: Grpc_Gateway_ProtocGenOpenapiv2_Options_Extensions_openapiv2_operation, value: newValue)}
  }
  /// Returns true if extension `Grpc_Gateway_ProtocGenOpenapiv2_Options_Extensions_openapiv2_operation`
  /// has been explicitly set.
  var hasGrpc_Gateway_ProtocGenOpenapiv2_Options_openapiv2Operation: Bool {
    return hasExtensionValue(ext: Grpc_Gateway_ProtocGenOpenapiv2_Options_Extensions_openapiv2_operation)
  }
  /// Clears the value of extension `Grpc_Gateway_ProtocGenOpenapiv2_Options_Extensions_openapiv2_operation`.
  /// Subsequent reads from it will return its default value.
  mutating func clearGrpc_Gateway_ProtocGenOpenapiv2_Options_openapiv2Operation() {
    clearExtensionValue(ext: Grpc_Gateway_ProtocGenOpenapiv2_Options_Extensions_openapiv2_operation)
  }
}

extension SwiftProtobuf.Google_Protobuf_ServiceOptions {

  /// ID assigned by protobuf-global-extension-registry@google.com for gRPC-Gateway project.
  ///
  /// All IDs are the same, as assigned. It is okay that they are the same, as they extend
  /// different descriptor messages.
  var Grpc_Gateway_ProtocGenOpenapiv2_Options_openapiv2Tag: Grpc_Gateway_ProtocGenOpenapiv2_Options_Tag {
    get {return getExtensionValue(ext: Grpc_Gateway_ProtocGenOpenapiv2_Options_Extensions_openapiv2_tag) ?? Grpc_Gateway_ProtocGenOpenapiv2_Options_Tag()}
    set {setExtensionValue(ext: Grpc_Gateway_ProtocGenOpenapiv2_Options_Extensions_openapiv2_tag, value: newValue)}
  }
  /// Returns true if extension `Grpc_Gateway_ProtocGenOpenapiv2_Options_Extensions_openapiv2_tag`
  /// has been explicitly set.
  var hasGrpc_Gateway_ProtocGenOpenapiv2_Options_openapiv2Tag: Bool {
    return hasExtensionValue(ext: Grpc_Gateway_ProtocGenOpenapiv2_Options_Extensions_openapiv2_tag)
  }
  /// Clears the value of extension `Grpc_Gateway_ProtocGenOpenapiv2_Options_Extensions_openapiv2_tag`.
  /// Subsequent reads from it will return its default value.
  mutating func clearGrpc_Gateway_ProtocGenOpenapiv2_Options_openapiv2Tag() {
    clearExtensionValue(ext: Grpc_Gateway_ProtocGenOpenapiv2_Options_Extensions_openapiv2_tag)
  }

}

// MARK: - File's ExtensionMap: Grpc_Gateway_ProtocGenOpenapiv2_Options_Annotations_Extensions

/// A `SwiftProtobuf.SimpleExtensionMap` that includes all of the extensions defined by
/// this .proto file. It can be used any place an `SwiftProtobuf.ExtensionMap` is needed
/// in parsing, or it can be combined with other `SwiftProtobuf.SimpleExtensionMap`s to create
/// a larger `SwiftProtobuf.SimpleExtensionMap`.
let Grpc_Gateway_ProtocGenOpenapiv2_Options_Annotations_Extensions: SwiftProtobuf.SimpleExtensionMap = [
  Grpc_Gateway_ProtocGenOpenapiv2_Options_Extensions_openapiv2_swagger,
  Grpc_Gateway_ProtocGenOpenapiv2_Options_Extensions_openapiv2_operation,
  Grpc_Gateway_ProtocGenOpenapiv2_Options_Extensions_openapiv2_schema,
  Grpc_Gateway_ProtocGenOpenapiv2_Options_Extensions_openapiv2_tag,
  Grpc_Gateway_ProtocGenOpenapiv2_Options_Extensions_openapiv2_field
]

// Extension Objects - The only reason these might be needed is when manually
// constructing a `SimpleExtensionMap`, otherwise, use the above _Extension Properties_
// accessors for the extension fields on the messages directly.

/// ID assigned by protobuf-global-extension-registry@google.com for gRPC-Gateway project.
///
/// All IDs are the same, as assigned. It is okay that they are the same, as they extend
/// different descriptor messages.
let Grpc_Gateway_ProtocGenOpenapiv2_Options_Extensions_openapiv2_swagger = SwiftProtobuf.MessageExtension<SwiftProtobuf.OptionalMessageExtensionField<Grpc_Gateway_ProtocGenOpenapiv2_Options_Swagger>, SwiftProtobuf.Google_Protobuf_FileOptions>(
  _protobuf_fieldNumber: 1042,
  fieldName: "grpc.gateway.protoc_gen_openapiv2.options.openapiv2_swagger"
)

/// ID assigned by protobuf-global-extension-registry@google.com for gRPC-Gateway project.
///
/// All IDs are the same, as assigned. It is okay that they are the same, as they extend
/// different descriptor messages.
let Grpc_Gateway_ProtocGenOpenapiv2_Options_Extensions_openapiv2_operation = SwiftProtobuf.MessageExtension<SwiftProtobuf.OptionalMessageExtensionField<Grpc_Gateway_ProtocGenOpenapiv2_Options_Operation>, SwiftProtobuf.Google_Protobuf_MethodOptions>(
  _protobuf_fieldNumber: 1042,
  fieldName: "grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation"
)

/// ID assigned by protobuf-global-extension-registry@google.com for gRPC-Gateway project.
///
/// All IDs are the same, as assigned. It is okay that they are the same, as they extend
/// different descriptor messages.
let Grpc_Gateway_ProtocGenOpenapiv2_Options_Extensions_openapiv2_schema = SwiftProtobuf.MessageExtension<SwiftProtobuf.OptionalMessageExtensionField<Grpc_Gateway_ProtocGenOpenapiv2_Options_Schema>, SwiftProtobuf.Google_Protobuf_MessageOptions>(
  _protobuf_fieldNumber: 1042,
  fieldName: "grpc.gateway.protoc_gen_openapiv2.options.openapiv2_schema"
)

/// ID assigned by protobuf-global-extension-registry@google.com for gRPC-Gateway project.
///
/// All IDs are the same, as assigned. It is okay that they are the same, as they extend
/// different descriptor messages.
let Grpc_Gateway_ProtocGenOpenapiv2_Options_Extensions_openapiv2_tag = SwiftProtobuf.MessageExtension<SwiftProtobuf.OptionalMessageExtensionField<Grpc_Gateway_ProtocGenOpenapiv2_Options_Tag>, SwiftProtobuf.Google_Protobuf_ServiceOptions>(
  _protobuf_fieldNumber: 1042,
  fieldName: "grpc.gateway.protoc_gen_openapiv2.options.openapiv2_tag"
)

/// ID assigned by protobuf-global-extension-registry@google.com for gRPC-Gateway project.
///
/// All IDs are the same, as assigned. It is okay that they are the same, as they extend
/// different descriptor messages.
let Grpc_Gateway_ProtocGenOpenapiv2_Options_Extensions_openapiv2_field = SwiftProtobuf.MessageExtension<SwiftProtobuf.OptionalMessageExtensionField<Grpc_Gateway_ProtocGenOpenapiv2_Options_JSONSchema>, SwiftProtobuf.Google_Protobuf_FieldOptions>(
  _protobuf_fieldNumber: 1042,
  fieldName: "grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field"
)
